[bash.files."bash/.bashrc"]
target = "~/.bashrc"
type = "template"
append = """
# Automatically appended by dotter
export HTTP_PROXY='http://127.0.0.1:8079'
export HTTPS_PROXY='http://127.0.0.1:8079'
"""
