[class]
image_default = [
    { command = "xdg-open", fork = true, silent = true },
    { command = "feh", args = [
        "--auto-zoom",
        "-x",
        "--borderless",
        "--image-bg",
        "black",
        "--scale-down",
        "--start-at",
    ], fork = true, silent = true },
    { command = "krita", fork = true, silent = true },
    { command = "xclip", args=[
        "-selection",
        "clipboard",
        "-target",
        "image/png",
        "-i",
    ], fork =true, silint=false }
]

text_default = [
    { command = "nvim", fork = false, silent = false },
    { command = "xdg-open", fork = true, silent = true },
    { command = "vim", fork = false, silent = false },
    { command = "gedit", fork = true, silent = true },
]

any = [
    { command = "xdg-open", fork = true, silent = true },
    { command = "xdg-open" },
    { command = "file", args = [
        "--mime-type",
        "-L",
        "-b",
    ], fork = false, silent = false, confirm_exit = true },
    { command = "no_spaces" },
]

directory = [
    { command = "alacritty", args = [
        "--working-directory",
    ] },
    { command = "zip", args = [
        "-r",
        "out.zip",
    ] },
    { command = "no_spaces" },
]

audio_default = [{ command = "vlc", fork = true, silent = true }]
[extension]

## audio formats
aac.inherit = "audio_default"
ac3.inherit = "audio_default"
aiff.inherit = "audio_default"
ape.inherit = "audio_default"
dts.inherit = "audio_default"
flac.inherit = "audio_default"
m4a.inherit = "audio_default"
mp3.inherit = "audio_default"
oga.inherit = "audio_default"
ogg.inherit = "audio_default"
opus.inherit = "audio_default"
wav.inherit = "audio_default"
wv.inherit = "audio_default"

[mimetype]

[mimetype.inode]
inherit = "directory"

[mimetype.image]
inherit = "image_default"
# text/*
[mimetype.text]
inherit = "text_default"

[mimetype.application]
inherit = "any"
