[class]
image_default	= [
    { command = "xdg-open", fork = true, silent = true },
	{ command = "feh", args = ["--auto-zoom", "-x", "--borderless", "--image-bg", "black", "--scale-down", "--start-at"], fork = true, silent = true },
	{ command = "gimp", fork = true, silent = true },
	{ command = "krita", fork = true, silent = true },
]

text_default    = [
	{ command = "nvim", fork = false, silent = false },
    { command = "xdg-open", fork = true, silent = true },
	{ command = "vim", fork = false, silent = false },
	{ command = "gedit", fork = true, silent = true },
]

any             = [
    { command = "xdg-open", fork = true, silent = true },
	{ command = "xdg-open" },
	{ command = "file", args = ["--mime-type", "-L", "-b"], fork = false, silent = false, confirm_exit = true },
	{ command = "no_spaces" },
	]

directory       = [
	{ command = "alacritty", args = ["--working-directory"] },
	{ command = "zip", args = ["-r", "out.zip"] },
	{ command = "no_spaces" },
]

[extension]

[mimetype]

[mimetype.inode]
inherit = "directory"

[mimetype.image]
inherit = "image_default"
# text/*
[mimetype.text]
inherit = "text_default"

[mimetype.application]
inherit = "any"
