#!/bin/bash
# On my pc one of my RAM cards can disable after boot
# So i need a way to detect it (on windows had the same issue)
RAM=$(sudo cat /proc/meminfo | grep -oP "MemTotal:\ *\K[0-9]*")
LOWRAM="16319596"
if [ "$RAM" = "$LOWRAM" ]; then 
    echo "one of RAM cards randomly disabled:"
    free
    echo "Reboot?(y = yes)"
    read
    if [ "$REPLY" = "y" ]; then
        sudo reboot
    fi
fi
