[helpers]


[default]
depends = [
    "i3",
    "bash",
    "gedit",
    "mime",
    "alacritty",
    "nvim",
    "rofi",
    "tms",
    "tmux",
    "joshuto",
    "cargo",
    "polybar",
    "clipcat",
]

# all packages not included in the default package
[nondefault]
depends = []

# clipboard manager written in rust
[clipcat.files]
clipcat = "~/.config/clipcat"

# packet manager for rust programming language
[cargo.files]
cargo = "~/.cargo"

# terminal
[alacritty.files]
alacritty = "~/.config/alacritty"

# terminal editor
[nvim.files]
nvim = "~/.config/nvim"

# runs .desktop files and scripts with fuzzy finding
[rofi.files]
rofi = "~/.config/rofi"

# tmux sessionizer 
# (fuzzy find projects containing .git and create tmux sessions)
[tms.files]
tms = "~/.config/tms"

# terminal multiplexer (multiple windows/splits/sessions in one terminal)
[tmux.files]
"tmux/tmux.conf" = "~/.config/tmux/tmux.conf"

# tiled window manager
[i3.files]
"xinitrc/.xinitrc" = "~/.xinitrc"
i3 = "~/.config/i3"
picom = "~/.config/picom"
dunst = "~/.config/dunst"

[polybar.files]
polybar = "~/.config/polybar"

[polybar.variables]
# additional modules right (prepend to existing modules)
modules_right = ""

# graphical text editor (like notepad for linux)
[gedit.files]
gedit = "~/.local/share/gedit/styles"

[bash.files]
"bash/.bashrc" = "~/.bashrc"
"bash/.bash_profile" = "~/.bash_profile"
"bash/scripts" = "~/.local/bin"

# Terminal filemanager
[joshuto.files]
joshuto = "~/.config/joshuto"

[mime.files]
"mime/desktop" = "~/.local/share/applications"
# I don't want applications just rewrite my mimeapps.list without me knowing it
"mime/mimeapps.list" = { target = "~/.config/mimeapps.list", type = "template" }

[default.variables]
