[helpers]


[default]
depends = [
    "alacritty",
    "nvim",
    "cargo",
    "youtubedl",
    "zed",
    "hyprland",
    "zsh",
    "scripts",
    "waybar"
]

[waybar.files]
waybar = "~/.config/waybar"

# my scripts (mostly bash)
[scripts.files]
scripts = "~/.local/bin"

# tiling wm for wayland
[hyprland.files]
hyprland = "~/.config/hypr"

# best editor
[zed.files]
zed = "~/.config/zed"

# vim emulation plugins for jetbrains settings
[ideavim.files]
ideavim = "~/"

# youtube video downloader
[youtubedl.files]
youtubedl = "~/.config"

# clipboard manager written in rust
[clipcat.files]
clipcat = "~/.config/clipcat"

# packet manager for rust programming language
[cargo.files]
cargo = "~/.cargo"

# terminal
[alacritty.files]
alacritty = "~/.config/alacritty"

# terminal editor
[nvim.files]
nvim = "~/.config/nvim"

# runs .desktop files and scripts with fuzzy finding
[rofi.files]
rofi = "~/.config/rofi"

# tmux sessionizer 
# (fuzzy find projects containing .git and create tmux sessions)
[tms.files]
tms = "~/.config/tms"

# terminal multiplexer (multiple windows/splits/sessions in one terminal)
[tmux.files]
"tmux/tmux.conf" = "~/.config/tmux/tmux.conf"

# tiled window manager
[i3.files]
"xinitrc/.xinitrc" = "~/.xinitrc"
i3 = "~/.config/i3"
picom = "~/.config/picom"
dunst = "~/.config/dunst"

[polybar.files]
polybar = "~/.config/polybar"

[polybar.variables]
# additional modules right (prepend to existing modules)
modules_right = ""

# graphical text editor (like notepad for linux)
[gedit.files]
gedit = "~/.local/share/gedit/styles"

[zsh.files]
zsh = "~/"

[bash.files]
"bash/.bashrc" = "~/.bashrc"
"bash/.bash_profile" = "~/.bash_profile"

# Terminal filemanager
[joshuto.files]
joshuto = "~/.config/joshuto"

[mime.files]
"mime/desktop" = "~/.local/share/applications"
# I don't want applications just rewrite my mimeapps.list without me knowing it
"mime/mimeapps.list" = { target = "~/.config/mimeapps.list", type = "template" }

[default.variables]
